
const seedProducts=[
{id:"1001",name:"Premium Coffee",category:"Coffee",price:120,stock:18,image:"https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=700&q=80"},
{id:"1002",name:"Classic Burger",category:"Food",price:185,stock:12,image:"https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=700&q=80"},
{id:"1003",name:"Fresh Juice",category:"Drinks",price:90,stock:25,image:"https://images.unsplash.com/photo-1600271886742-f049cd451bba?w=700&q=80"},
{id:"1004",name:"Chocolate Cake",category:"Desserts",price:150,stock:7,image:"https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=700&q=80"}];

var $=function(s){return document.querySelector(s)};
var getProducts=function(){var x=localStorage.getItem("shishti_products");if(x===null){localStorage.setItem("shishti_products",JSON.stringify(seedProducts));return seedProducts}try{return JSON.parse(x)||[]}catch(e){return[]}};
var saveProducts=function(p){localStorage.setItem("shishti_products",JSON.stringify(p))};
var getOrders=function(){try{return JSON.parse(localStorage.getItem("shishti_orders")||"[]")}catch(e){return[]}};
var getUsers=function(){try{return JSON.parse(localStorage.getItem("shishti_users")||"[]")}catch(e){return[]}};
var saveUsers=function(u){localStorage.setItem("shishti_users",JSON.stringify(u))};
var currentUser=function(){var id=localStorage.getItem("shishti_current_user");return getUsers().find(function(u){return u.id===id})||null};
var money=function(n){return "EGP "+Number(n||0).toLocaleString("en-EG",{maximumFractionDigits:0})};
var placeholder=function(){return "https://placehold.co/700x700/171717/ffffff?text=SHISHTI"};
var escapeHtml=function(s){return String(s==null?"":s).replace(/[&<>"']/g,function(c){return {"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]})};
var toast=function(m){var t=$("#toast");if(!t)return;t.textContent=m;t.classList.add("show");setTimeout(function(){t.classList.remove("show")},2200)};
var cart=JSON.parse(localStorage.getItem("shishti_cart")||"[]");
var activeCategory="All",authMode="login",scannerStream=null,scannerTimer=null;

var LANG={
en:{navShop:"Shop",navAbout:"About",online:"SHISHTI ONLINE",heroTitle:"Everything you want.<br><span>One place.</span>",heroText:"Discover the SHISHTI collection, add what you need to your cart and place your order in a few simple steps.",explore:"Explore products",createAccount:"Create account",fast:"Fast ordering",customerAccount:"Customer account",liveStock:"Live stock",collection:"COLLECTION",shopProducts:"Shop products",search:"Search products...",yourAccount:"YOUR SHISHTI ACCOUNT",orderFaster:"Order faster next time.",accountText:"Save your details, view your demo orders and keep your shopping experience in one place.",openAccount:"Open account",yourBag:"YOUR BAG",shoppingCart:"Shopping cart",total:"Total",checkout:"Continue to checkout",account:"SHISHTI ACCOUNT",signIn:"Sign in",fullName:"Full name",email:"Email",password:"Password",demoStorage:"Demo only: account data is stored in this browser's localStorage.",myAccount:"MY ACCOUNT",viewOrders:"View my orders",signOut:"Sign out",completeOrder:"Complete your order",phone:"Phone number",address:"Delivery address",payment:"Payment method",cod:"Cash on delivery",onlineDemo:"Online payment (demo)",placeOrder:"Place order",controlCenter:"STORE CONTROL CENTER",adminDashboard:"ADMIN DASHBOARD",runStore:"Run your store.",adminText:"Manage inventory, scan products, review orders and keep the online store synchronized.",scanAdd:"＋ Scan & add product",products:"PRODUCTS",liveInStore:"Live in store",orders:"ORDERS",allOrders:"All customer orders",pending:"PENDING",needAttention:"Need attention",sales:"SALES",demoSales:"Demo order value",inventory:"INVENTORY",addManually:"＋ Add manually",product:"Product",category:"Category",price:"Price",stock:"Stock",status:"Status",customerActivity:"CUSTOMER ACTIVITY",recentOrders:"Recent orders",scanner:"INVENTORY SCANNER",scanProduct:"Scan a product",scannerText:"Scan the barcode or QR code on the package. We will try to find public product information, then you add your own price and quantity.",barcode:"Enter barcode manually",lookup:"Lookup",productName:"Product name",yourPrice:"Your price (EGP)",quantity:"Quantity in stock",imageUrl:"Image URL",saveProduct:"Save product",account:"SHISHTI ACCOUNT"},
ar:{navShop:"المتجر",navAbout:"عن شِشتي",online:"متجر شِشتي",heroTitle:"كل ما تحتاجه.<br><span>في مكان واحد.</span>",heroText:"اكتشف منتجات شِشتي، أضف ما تحتاجه إلى السلة ونفّذ طلبك في خطوات بسيطة.",explore:"استعرض المنتجات",createAccount:"إنشاء حساب",fast:"طلب سريع",customerAccount:"حساب عميل",liveStock:"مخزون محدث",collection:"المجموعة",shopProducts:"تصفح المنتجات",search:"ابحث عن منتج...",yourAccount:"حساب شِشتي",orderFaster:"اطلب أسرع في المرة القادمة.",accountText:"احفظ بياناتك وشاهد طلباتك واجعل تجربة التسوق كلها في مكان واحد.",openAccount:"فتح الحساب",yourBag:"سلتك",shoppingCart:"سلة التسوق",total:"الإجمالي",checkout:"متابعة الدفع",account:"حساب شِشتي",signIn:"تسجيل الدخول",fullName:"الاسم الكامل",email:"البريد الإلكتروني",password:"كلمة المرور",demoStorage:"نسخة تجريبية: بيانات الحساب محفوظة في localStorage على هذا المتصفح.",myAccount:"حسابي",viewOrders:"عرض طلباتي",signOut:"تسجيل الخروج",completeOrder:"إكمال الطلب",phone:"رقم الهاتف",address:"عنوان التوصيل",payment:"طريقة الدفع",cod:"الدفع عند الاستلام",onlineDemo:"الدفع الإلكتروني (تجريبي)",placeOrder:"تأكيد الطلب",controlCenter:"مركز تحكم المتجر",adminDashboard:"لوحة تحكم الإدارة",runStore:"أدر متجرك.",adminText:"أدر المخزون، امسح المنتجات، راجع الطلبات وحافظ على تزامن المتجر الإلكتروني.",scanAdd:"＋ مسح وإضافة منتج",products:"المنتجات",liveInStore:"المنتجات المعروضة",orders:"الطلبات",allOrders:"كل طلبات العملاء",pending:"قيد الانتظار",needAttention:"تحتاج متابعة",sales:"المبيعات",demoSales:"قيمة الطلبات التجريبية",inventory:"المخزون",addManually:"＋ إضافة يدويًا",product:"المنتج",category:"التصنيف",price:"السعر",stock:"المخزون",status:"الحالة",customerActivity:"نشاط العملاء",recentOrders:"أحدث الطلبات",scanner:"ماسح المخزون",scanProduct:"مسح منتج",scannerText:"امسح الباركود أو QR على العبوة. سنحاول جلب بيانات المنتج من الإنترنت ثم تضيف السعر والكمية.",barcode:"أدخل الباركود يدويًا",lookup:"بحث",productName:"اسم المنتج",yourPrice:"السعر (جنيه)",quantity:"الكمية المتوفرة",imageUrl:"رابط الصورة",saveProduct:"حفظ المنتج"}};
var currentLang=localStorage.getItem("shishti_lang")||"en";
function applyLanguage(){
 var d=LANG[currentLang];document.documentElement.lang=currentLang;document.documentElement.dir=currentLang==="ar"?"rtl":"ltr";
 document.querySelectorAll("[data-i18n]").forEach(function(el){var k=el.dataset.i18n;if(d[k]!=null)el.textContent=d[k]});
 document.querySelectorAll("[data-i18n-html]").forEach(function(el){var k=el.dataset.i18nHtml;if(d[k]!=null)el.innerHTML=d[k]});
 document.querySelectorAll("[data-i18n-placeholder]").forEach(function(el){var k=el.dataset.i18nPlaceholder;if(d[k]!=null)el.placeholder=d[k]});
 var b=$("#langBtn");if(b)b.textContent=currentLang==="en"?"العربية":"English";
 document.title=currentLang==="ar"?"شِشتي | المتجر":"SHISHTI | Online Store";
 if(document.body.dataset.page==="admin")document.title=currentLang==="ar"?"شِشتي | لوحة التحكم":"SHISHTI | Admin Dashboard";
}
function toggleLanguage(){currentLang=currentLang==="en"?"ar":"en";localStorage.setItem("shishti_lang",currentLang);applyLanguage();renderCategories();renderProducts();if(document.body.dataset.page==="admin"){renderInventory();renderOrders()}}


if(document.body.dataset.page==="store")initStore();
if(document.body.dataset.page==="admin")initAdmin();

function initStore(){
 applyLanguage();var lb=$("#langBtn");if(lb)lb.onclick=toggleLanguage;
 $("#checkoutForm").onsubmit=placeOrder;
 renderCategories();renderProducts();updateCartCount();updateAccountButton();
 $("#search").addEventListener("input",renderProducts);
 $("#cartBtn").onclick=openCart;$("#closeCart").onclick=closeCart;$("#overlay").onclick=closeCart;
 $("#checkoutBtn").onclick=function(){if(!cart.length)return toast(currentLang==="ar"?"السلة فارغة":"Your cart is empty");if(!currentUser()){openAccount("login");return toast(currentLang==="ar"?"سجّل الدخول أولاً لإكمال الطلب":"Sign in before checkout")}openCheckout()};
 $("#accountBtn").onclick=function(){openAccount()};
 $("#heroAccount").onclick=function(){openAccount("register")};
 $("#stripAccount").onclick=function(){openAccount()};
 $("#loginTab").onclick=function(){setAuthMode("login")};$("#registerTab").onclick=function(){setAuthMode("register")};
 $("#authForm").onsubmit=handleAuth;$("#logoutBtn").onclick=logout;$("#ordersBtn").onclick=renderAccountOrders;
 document.querySelectorAll("[data-close]").forEach(function(b){b.onclick=function(){closeModal(b.dataset.close)}});
 window.addEventListener("storage",syncStore);
}
function syncStore(e){if(["shishti_products","shishti_orders","shishti_current_user","shishti_users"].indexOf(e.key)>=0){renderCategories();renderProducts();updateAccountButton();if($("#accountModal").classList.contains("show"))refreshAccountView()}}
function renderCategories(){var cats=[currentLang==="ar"?"الكل":"All"].concat(Array.from(new Set(getProducts().map(function(p){return p.category}).filter(Boolean))));$("#categories").innerHTML=cats.map(function(c){return '<button class="chip '+(c===activeCategory?"active":"")+'" data-cat="'+escapeHtml(c)+'">'+escapeHtml(c)+"</button>"}).join("");document.querySelectorAll("[data-cat]").forEach(function(b){b.onclick=function(){activeCategory=b.dataset.cat;renderCategories();renderProducts()}})}
function renderProducts(){var q=(($("#search")&&$("#search").value)||"").toLowerCase();var ps=getProducts().filter(function(p){return((activeCategory==="All"||activeCategory==="الكل"||p.category===activeCategory))&&p.name.toLowerCase().indexOf(q)>=0});$("#productGrid").innerHTML=ps.map(function(p){return '<article class="product-card"><div class="product-img"><img src="'+(p.image||placeholder())+'" alt="'+escapeHtml(p.name)+'" onerror="this.src=\\''+placeholder()+'\\'"></div><div class="product-info"><small>'+escapeHtml(p.category||"General")+'</small><h3>'+escapeHtml(p.name)+'</h3><div class="price-row"><span class="price">'+money(p.price)+'</span><button class="add-btn" onclick="addToCart(\\''+p.id+'\\')">+</button></div></div></article>'}).join("")||'<div class="empty">'+(currentLang==="ar"?"لا توجد منتجات.":"No products found.")+'</div>'}
function addToCart(id){var p=getProducts().find(function(x){return x.id===id});if(!p||p.stock<1)return toast(currentLang==="ar"?"المنتج غير متوفر":"Product is out of stock");var x=cart.find(function(i){return i.id===id});if(x){if(x.qty>=p.stock)return toast(currentLang==="ar"?"لا توجد كمية إضافية متاحة":"No more stock available");x.qty++}else cart.push({id:id,qty:1});saveCart();updateCartCount();toast(currentLang==="ar"?"تمت إضافة المنتج للسلة":"Added to cart")}
function saveCart(){localStorage.setItem("shishti_cart",JSON.stringify(cart))}
function updateCartCount(){$("#cartCount").textContent=cart.reduce(function(a,b){return a+b.qty},0)}
function openCart(){renderCart();$("#cartDrawer").classList.add("open");$("#overlay").classList.add("show")}
function closeCart(){$("#cartDrawer").classList.remove("open");$("#overlay").classList.remove("show")}
function renderCart(){var ps=getProducts(),total=0;$("#cartItems").innerHTML=cart.map(function(i){var p=ps.find(function(x){return x.id===i.id});if(!p)return"";total+=p.price*i.qty;return '<div class="cart-row"><img src="'+(p.image||placeholder())+'"><div><strong>'+escapeHtml(p.name)+'</strong><div class="qty"><button onclick="changeQty(\\''+p.id+'\\',-1)">−</button>'+i.qty+'<button onclick="changeQty(\\''+p.id+'\\',1)">+</button></div></div><b>'+money(p.price*i.qty)+'</b></div>'}).join("")||'<div class="empty" style="margin-top:20px">Your cart is empty.</div>';$("#cartTotal").textContent=money(total)}
function changeQty(id,d){var p=getProducts().find(function(x){return x.id===id}),i=cart.find(function(x){return x.id===id});if(!i)return;i.qty+=d;if(i.qty<=0)cart=cart.filter(function(x){return x.id!==id});if(p&&i.qty>p.stock)i.qty=p.stock;saveCart();updateCartCount();renderCart()}
function openCheckout(){var u=currentUser();$("#checkoutName").value=u?u.name:"";openModal("checkoutModal")}
function placeOrder(e){e.preventDefault();var u=currentUser();if(!u)return openAccount("login");var f=new FormData(e.target),products=getProducts();var items=cart.map(function(i){var p=products.find(function(x){return x.id===i.id});return{id:p.id,name:p.name,qty:i.qty,price:p.price}});var total=items.reduce(function(a,i){return a+i.price*i.qty},0);var orders=getOrders();orders.unshift({id:"S-"+Date.now().toString().slice(-6),userId:u.id,customer:f.get("name"),email:u.email,phone:f.get("phone"),address:f.get("address"),payment:f.get("payment"),items:items,total:total,status:"Pending",date:new Date().toLocaleString()});localStorage.setItem("shishti_orders",JSON.stringify(orders));saveProducts(products.map(function(p){var i=cart.find(function(x){return x.id===p.id});return i?Object.assign({},p,{stock:Math.max(0,p.stock-i.qty)}):p}));cart=[];saveCart();updateCartCount();e.target.reset();closeModal("checkoutModal");closeCart();toast(currentLang==="ar"?"تم إرسال الطلب بنجاح":"Order placed successfully")}
function openAccount(mode){if(mode)setAuthMode(mode);refreshAccountView();openModal("accountModal")}
function refreshAccountView(){var u=currentUser();$("#authView").classList.toggle("hidden",!!u);$("#profileView").classList.toggle("hidden",!u);if(u){$("#profileName").textContent=u.name;$("#profileEmail").textContent=u.email;renderAccountOrders()}}
function updateAccountButton(){var u=currentUser();$("#accountBtn").textContent=u?u.name.split(" ")[0]:(currentLang==="ar"?"الحساب":"Account")}
function setAuthMode(mode){authMode=mode;$("#loginTab").classList.toggle("active",mode==="login");$("#registerTab").classList.toggle("active",mode==="register");$("#nameField").classList.toggle("hidden",mode!=="register");$("#nameField input").required=mode==="register";$("#authTitle").textContent=mode==="register"?"Create your account":"Welcome back";$("#authSubtitle").textContent=mode==="register"?"Create a local demo account to save your shopping details.":"Sign in to save your details and view your orders.";$("#authSubmit").textContent=mode==="register"?"Create account":"Sign in";$("#authForm").reset()}
function handleAuth(e){e.preventDefault();var f=new FormData(e.target),email=String(f.get("email")||"").trim().toLowerCase(),password=String(f.get("password")||"");if(!email||!password)return toast(currentLang==="ar"?"أدخل البريد وكلمة المرور":"Enter email and password");var users=getUsers();if(authMode==="register"){if(users.some(function(u){return u.email===email}))return toast(currentLang==="ar"?"هذا البريد مسجل بالفعل":"An account with this email already exists");var u={id:"U-"+Date.now(),name:String(f.get("name")).trim(),email:email,password:password};users.push(u);saveUsers(users);localStorage.setItem("shishti_current_user",u.id);refreshAccountView();updateAccountButton();toast(currentLang==="ar"?"تم إنشاء الحساب":"Account created")}else{var u2=users.find(function(x){return x.email===email&&x.password===password});if(!u2)return toast(currentLang==="ar"?"البريد أو كلمة المرور غير صحيحة":"Email or password is incorrect");localStorage.setItem("shishti_current_user",u2.id);refreshAccountView();updateAccountButton();toast(currentLang==="ar"?"تم تسجيل الدخول":"Signed in")}}
function logout(){localStorage.removeItem("shishti_current_user");refreshAccountView();updateAccountButton();toast(currentLang==="ar"?"تم تسجيل الخروج":"Signed out")}
function renderAccountOrders(){var u=currentUser();if(!u)return;var orders=getOrders().filter(function(o){return o.userId===u.id});$("#accountOrders").innerHTML=orders.length?orders.map(function(o){return '<div class="mini-order"><b>'+o.id+" · "+money(o.total)+'</b><span>'+o.status+" · "+o.date+"</span></div>"}).join(""):'<div class="mini-order">No orders yet.</div>'}

function initAdmin(){
 applyLanguage();var lb=$("#langBtn");if(lb)lb.onclick=toggleLanguage;
 renderInventory();renderOrders();updateStats();
 $("#addManual").onclick=function(){openProductModal()};
 $("#openScanner").onclick=function(){openModal("scannerModal");startScanner()};
 $("#lookupBarcode").onclick=function(){lookupBarcode($("#barcodeInput").value.trim())};
 $("#adminLogout").onclick=function(){toast("Admin demo session closed")};
 $("#productForm").onsubmit=saveProduct;
 document.querySelectorAll("[data-close]").forEach(function(b){b.onclick=function(){closeModal(b.dataset.close)}});
 window.addEventListener("storage",syncAdmin);
}
function syncAdmin(e){if(["shishti_products","shishti_orders"].indexOf(e.key)>=0){renderInventory();renderOrders();updateStats()}}
function renderInventory(){var p=getProducts();$("#inventory").innerHTML=p.map(function(x){return '<tr><td><div class="table-product"><img src="'+(x.image||placeholder())+'"><div><strong>'+escapeHtml(x.name)+'</strong><small>'+escapeHtml(x.id)+'</small></div></div></td><td>'+escapeHtml(x.category||"General")+'</td><td>'+money(x.price)+'</td><td>'+x.stock+'</td><td><span class="status '+(x.stock<5?"low":"")+'">'+(x.stock<5?"Low stock":"In stock")+'</span></td><td><button class="action-btn" onclick="editProduct(\\''+x.id+'\\')">Edit</button></td></tr>'}).join("")}
function renderOrders(){var o=getOrders();$("#orders").innerHTML=o.length?o.slice(0,10).map(function(x){return '<div class="order"><div><strong>'+x.id+" · "+escapeHtml(x.customer)+'</strong><p>'+x.items.map(function(i){return i.qty+"× "+escapeHtml(i.name)}).join(", ")+'</p><p>'+escapeHtml(x.address)+" · "+escapeHtml(x.phone)+'</p></div><div style="text-align:right"><b>'+money(x.total)+'</b><p>'+escapeHtml(x.status)+"</p></div></div>"}).join(""):'<div class="empty">No orders yet. Orders placed from the store appear here automatically.</div>'}
function updateStats(){var p=getProducts(),o=getOrders();$("#statProducts").textContent=p.length;$("#statOrders").textContent=o.length;$("#statPending").textContent=o.filter(function(x){return x.status==="Pending"}).length;$("#statSales").textContent=money(o.reduce(function(a,x){return a+x.total},0))}
function openProductModal(product){var exists=product&&getProducts().some(function(x){return x.id===product.id});$("#productModalTitle").textContent=exists?"Edit product":"Add product";var f=$("#productForm");f.reset();f.elements.id.value=product&&product.id||"";f.elements.name.value=product&&product.name||"";f.elements.category.value=product&&product.category||"";f.elements.price.value=product&&product.price||"";f.elements.stock.value=product&&product.stock||"";f.elements.image.value=product&&product.image||"";$("#previewName").textContent=product&&product.name||"New product";$("#previewImage").src=product&&product.image||placeholder();$("#previewSource").textContent=product&&product.source||"Manual product";openModal("productModal")}
function editProduct(id){openProductModal(getProducts().find(function(p){return p.id===id}))}
function saveProduct(e){e.preventDefault();var f=new FormData(e.target),p=getProducts(),id=f.get("id")||"P-"+Date.now();var productName=String(f.get("name")||"").trim();var price=Number(f.get("price"));var stock=Number(f.get("stock"));if(!productName||!Number.isFinite(price)||price<0||!Number.isFinite(stock)||stock<0)return toast(currentLang==="ar"?"أكمل بيانات المنتج بشكل صحيح":"Complete the product details correctly");var item={id:id,name:productName,category:f.get("category")||"General",price:price,stock:stock,image:f.get("image")||placeholder()};var idx=p.findIndex(function(x){return x.id===id});if(idx>=0)p[idx]=item;else p.unshift(item);saveProducts(p);closeModal("productModal");renderInventory();updateStats();toast(currentLang==="ar"?"تم حفظ المنتج ونشره في المتجر":"Product saved and published to the store")}
async function lookupBarcode(code){if(!code)return toast(currentLang==="ar"?"أدخل الباركود أولاً":"Enter a barcode first");$("#lookupStatus").textContent="Searching public product data...";try{var r=await fetch("https://world.openfoodfacts.org/api/v2/product/"+encodeURIComponent(code)+".json");var d=await r.json();if(!d.product||d.status===0){$("#lookupStatus").textContent="No public record found. You can still enter the product manually.";stopScanner();closeModal("scannerModal");return openProductModal({id:code,name:"",category:"General",price:"",stock:0,image:"",source:"Barcode scanned · manual details"})}var x=d.product;$("#lookupStatus").textContent="Product found. Add your SHISHTI price and stock.";stopScanner();closeModal("scannerModal");openProductModal({id:code,name:x.product_name||x.product_name_en||"Scanned product",category:x.categories_tags&&x.categories_tags[0]?x.categories_tags[0].replace("en:",""):"General",price:"",stock:0,image:x.image_front_url||x.image_url||"",source:"Barcode scanned · public product data"})}catch(e){$("#lookupStatus").textContent="Lookup failed. You can add the product manually.";stopScanner();closeModal("scannerModal");openProductModal({id:code,name:"Scanned product",category:"General",price:"",stock:0,image:"",source:"Barcode scanned · manual details"})}}
async function startScanner(){try{if(!("BarcodeDetector" in window)){$("#lookupStatus").textContent="Live scanning is not supported in this browser. Use the field below.";return}var detector=new BarcodeDetector({formats:["qr_code","ean_13","ean_8","upc_a","upc_e","code_128","code_39","itf"]});scannerStream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:"environment"}}});var v=$("#scannerVideo");v.srcObject=scannerStream;await v.play();scannerTimer=setInterval(async function(){try{var codes=await detector.detect(v);if(codes.length&&codes[0].rawValue){$("#barcodeInput").value=codes[0].rawValue;lookupBarcode(codes[0].rawValue)}}catch(e){}},500)}catch(e){$("#lookupStatus").textContent="Camera access is unavailable. Enter the barcode manually."}}
function stopScanner(){if(scannerTimer)clearInterval(scannerTimer);scannerTimer=null;if(scannerStream)scannerStream.getTracks().forEach(function(t){t.stop()});scannerStream=null}
function openModal(id){$("#"+id).classList.add("show")}
function closeModal(id){$("#"+id).classList.remove("show");if(id==="scannerModal")stopScanner()}
